services:
  mock-target-open:
    build:
      context: ./mock-target-open
    networks:
      - e2e-net
  mock-target-closed:
    build:
      context: ./mock-target-closed
    networks:
      - e2e-net

networks:
  e2e-net:
    driver: bridge
